sudo: required
language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
before_install: ./CI/travis.before_install.sh
install: ./CI/travis.install.sh
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi
  - mkdir build
  - cd src
script:
  - qmake && make -j2
  - cd ../build
  - if [ -z "${TRAVIS_OS_NAME}" ] || [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake .. && make -j2; fi
notifications:
  email: false
